name: Testing workflow
'on':
  workflow_call:
    secrets:
      secret_envs:
        description: if given, it's passed to the environments
        required: false

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Set build envs
        run: |
          cat >> "$GITHUB_ENV" << 'EOF'
          ${{ secrets.secret_envs }}
          EOF
          
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Set build envs
        run: |
          echo "Running..."
          
          
