name: Testing workflow
on:
  workflow_call:
    secrets:
      secret_envs:
        description: if given, it's passed to the environments
        required: false
  workflow_dispatch: 
  

jobs:
  Test:
    runs-on: [self-hosted]
    env:
      GITHUB_JOB_OVERRIDDEN: 12345
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set build envs
        run: |
          cat >> "$GITHUB_ENV" << 'EOF'
          CHECK_NAME=name
          ${{secrets.secret_envs}}
          EOF
      - name: A command
        run: |
          ls -la
          # shellcheck disable=SC2319
          echo "JOB_EXIT_CODE=$?" >> "$GITHUB_ENV"
      - name: Run another
        run: |
          echo "another one!"
